name: e_sound_reminder_app
description: Flutter project of smart reminder mobile app for elderly people

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  lottie: ^2.2.0
  package_info_plus: ^3.0.3
  # flutter_launcher_name: ^0.0.1
  day_picker: ^2.1.1
  shared_preferences: ^2.0.18
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_oss_licenses: ^2.0.1

flutter_launcher_name:
  name: "E Daily Reminder"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/i18n/
    - assets/images/
    - assets/lotties/