name: e_sound_reminder_app
description: Flutter project of smart reminder mobile app for elderly people

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+16

environment:
  sdk: '>=2.18.4 <3.0.0'

scripts:
  # run is a default script. To use it, simply type
  # in the command line: "rps" - that's all!
  run: "flutter run -t lib/main.dart"
  # you can define more commands like this: "rps gen"
  gen: "flutter pub run build_runner watch --delete-conflicting-outputs"
  # and even nest them!
  buildoutput:
    # You can use hooks to! (and even nest them!)
    $before: flutter pub get
    $after: echo "Build done!"
    android:
      # rps build android apk
      apk: 
        $before: echo "Building android apk..."
        $script: "flutter build --release apk --flavor production"
      # rps build android appbundle
      appbundle: "flutter build --release appbundle --flavor production"
      # and so on...
  # too long command? no problem! define alias using reference syntax!
  bab: $buildoutput android appbundle
  # as simple as typing "rps baa"
  baa: $buildoutput android apk
  # some commands may vary from platform to platform
  # but that's not a problem
  clear:
    # use the $script key to define platform specific scripts
    $script:
      # define the default script
      $default: rm -rf ./app/cache
      # And different script for the windows platform.
      $windows: rd /s /q app\cache
      # now "rps clear" will work on any platform!

  dev: flutter run # -d <device_id>
  dev-fresh: flutter run --no-fast-start # -d <device_id>
  profile: flutter run --profile
  devices: flutter devices
  install: flutter pub get
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
  uninstall: adb shell && pm uninstall org.tether.tether # (sometimes doesn't uninstall when debugging?)
  format: flutter dartfmt --line-length=120 .

  build-release-ios: flutter build ipa  --release # open under xcworkspace, not xcodeproj
  build-release-macos: flutter pub run build_runner build --delete-conflicting-outputs && flutter build macos --release
  build-release-android: flutter pub run build_runner build --delete-conflicting-outputs && flutter build apk --release

  # mobile development commands
  setup-ios: pod install && flutter precache --ios
  clean-ios: xcrun simctl delete unavailable
  list-ios: xcrun simctl list devices
  boot-ios: xcrun simctl boot #<device_id>
  list-android: emulator -list-avds
  boot-android: emulator -avd #<device_id>
  inspect-android: adb shell && run-as org.tether.tether # cache inspection
  log-android: adb logcat ActivityManager:I flutter:I *:S

  # configuration and troubleshooting
  init-repo: git submodule update --init --recursive
  reset-xcode: defaults delete com.apple.dt.Xcode
  dev-tools: flutter pub global run devtools
  cache-clean: pub cache repair && flutter pub cache repair
  upgrade-deps: flutter pub upgrade --major-versions
  init-platform-dirs: flutter create --org org.tether.tether
  enable-desktop: flutter config --enable-macos-desktop --enable-linux-desktop # --no-enable-<type>-desktop

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  lottie: ^2.2.0
  package_info_plus: ^3.0.3
  # flutter_launcher_name: ^0.0.1
  # day_picker: ^2.1.1
  shared_preferences: ^2.0.18
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  hive: ^2.0.5
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^9.3.2
  timezone: ^0.8.0
  page_transition: ^2.0.9
  day_night_time_picker: ^1.2.0+2
  flutter_animation_progress_bar: ^2.3.1
  auto_size_text: ^3.0.0
  delayed_display: ^2.0.0
  vs_scrollbar: ^0.2.1
  flutter_ringtone_player: ^3.2.0
  custom_refresh_indicator: ^2.0.1
  tutorial_coach_mark: ^1.2.8
  no_context_navigation: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_oss_licenses: ^2.0.1
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_android: "assets/images/app_icon_512.png"
  adaptive_icon_background: "assets/images/app_icon_background.png"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter_launcher_name:
  name: "E Daily Reminder"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/i18n/
    - assets/images/
    - assets/lotties/
    - assets/sounds/