name: e_sound_reminder_app
description: Flutter project of smart reminder mobile app for elderly people

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  lottie: ^2.2.0
  package_info_plus: ^3.0.3
  # flutter_launcher_name: ^0.0.1
  day_picker: ^2.1.1
  shared_preferences: ^2.0.18
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  hive: ^2.0.5
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_oss_licenses: ^2.0.1
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_android: "assets/images/app_icon_512.png"
  adaptive_icon_background: "assets/images/app_icon_background.png"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter_launcher_name:
  name: "E Daily Reminder"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/i18n/
    - assets/images/
    - assets/lotties/